### ISSUE TITLE
minor issues after PR #13

### ISSUE THREAD

**Issue by xoolive** [open-aviation/tangram#14]
- the `justfile` is outdated (should be `tangram run` for poetry)
- the `lockfile` is outdated (should run `poetry lock --no-update` and recommit)

Also, it seems the websocket is experiencing issues from http://51.158.72.24:8080 (don't have much time to investigate, ping on slack if needed)

**Comment by emctoo** [comment]
I noticed this recently and it's intermittent on my side. 

I'm on some updates of the source plugin. It's about streaming, I will also dig into this together.
